TRANSLATIONS = {
    "pt": {
        "app_title": "SQLite Workbench",
        "db_explorer": "Explorador DB",
        "load_db": "Carregar .DB",
        "import_csv": "Importar CSV",
        "new_table": "Nova Tabela",
        "compact_db": "Compactar DB",
        "search_placeholder": "Pesquisar tabela...",
        "tables": "Tabelas",
        "language": "Idioma",
        "theme": "Tema",
        "rows_per_page": "Linhas por pág.:",
        "no_file": "Nenhum ficheiro carregado.",
        "export_csv": "Exportar",
        "export_csv_label": "CSV (*.csv)",
        "export_json_label": "JSON (*.json)",
        "new_record": "Novo Registo",
        "tab_data": "Dados",
        "tab_schema": "Esquema",
        "tab_stats": "Estatísticas",
        "tab_sql": "SQL",
        "search_data_placeholder": "Pesquisar nos dados...",
        "search_btn": "Pesquisar",
        "clear_btn": "Limpar",
        "prev": "Anterior",
        "next": "Próxima",
        "page_of": "de",
        "lines": "linhas",
        "exec_sql": "Executar",
        "tab_history": "Histórico",
        "tab_favorites": "Favoritos",
        "footer_author": "Autor: Carlos Canuto Costa",
        "edit": "Editar",
        "delete": "Apagar",
        "rename": "Renomear",
        "warning": "Aviso",
        "error": "Erro",
        "success": "Sucesso",
        "confirm": "Confirmar",
        "db_empty_warning": "A base de dados está vazia. Pode importar um CSV.",
        "restart_msg": "Reinicie a aplicação para aplicar o novo idioma.",
        "load_db_first": "Carregue uma base de dados primeiro.",
        "enter_table_name": "Nome da nova tabela:",
        "vacuum_confirm": "Deseja compactar a base de dados (VACUUM)?\n\nEsta ação reescreve o ficheiro da base de dados para recuperar espaço não utilizado e pode demorar algum tempo.",
        "vacuum_success": "A base de dados foi compactada com sucesso.",
        "confirm_delete_record": "Tem a certeza que quer apagar o registo com rowid {}?",
        "confirm_delete_table": "Tem a certeza que quer apagar a tabela '{}'?\nEsta ação é irreversível.",
        "record_updated": "Registo atualizado.",
        "record_inserted": "Registo inserido com sucesso.",
        "export_success": "Exportado!",
        "no_data_export": "Não há dados para exportar nesta aba.",
        "tooltip_load_db": "Abrir um ficheiro de base de dados SQLite",
        "tooltip_import_csv": "Importar um ficheiro CSV para uma nova tabela",
        "tooltip_new_table": "Criar uma nova tabela vazia",
        "tooltip_vacuum": "Otimizar o tamanho da base de dados",
        "tooltip_export": "Exportar os dados visíveis para CSV ou JSON",
        "tooltip_new_record": "Inserir uma nova linha na tabela atual",
        "tooltip_run_sql": "Executar o comando SQL (Ctrl+Enter)",
        "cancel": "Cancelar",
        "save": "Guardar",
        "insert": "Inserir",
        "edit_values": "Editar Valores",
        "fill_values": "Preencher Valores",
        "rename_table_prompt": "Novo nome para a tabela '{}':",
        "no_stats_data": "Sem dados suficientes para estatísticas.",
        "no_columns_analyze": "Sem colunas para analisar.",
        "stats_table": "Tabela:",
        "stats_sample": "Amostra analisada:",
        "stats_filled": "preenchidos:",
        "stats_empty": "vazios:",
        "stats_top_values": "top valores:",
        "stats_no_data": "sem dados",
        "stats_error": "Erro ao gerar estatísticas: {}",
        "export_error": "Erro ao exportar: {}",
        "file_loaded": "Ficheiro:",
        "table_label": "Tabela:",
        "select_csv_title": "Selecionar Ficheiro CSV",
        "table_name_title": "Nome da Tabela",
        "btn_pandas_stats": "📊 Relatório Pandas",
        "title_pandas_stats": "Estatísticas Avançadas (Pandas)",
        "calculating_stats": "A calcular estatísticas...",
        "processing_column": "A processar coluna: {}",
        "op_cancelled": "Operação cancelada.",
        "stats_unique": "únicos:",
        "stats_min": "min:",
        "stats_max": "max:",
        "stats_avg": "média:",
        "export_stats_btn": "💾 Guardar JSON",
        "stats_saved": "Estatísticas exportadas para: {}",
    },
    "en": {
        "app_title": "SQLite Workbench",
        "db_explorer": "DB Explorer",
        "load_db": "Load .DB",
        "import_csv": "Import CSV",
        "new_table": "New Table",
        "compact_db": "Vacuum DB",
        "search_placeholder": "Search table...",
        "tables": "Tables",
        "language": "Language",
        "theme": "Theme",
        "rows_per_page": "Rows per page:",
        "no_file": "No file loaded.",
        "export_csv": "Export",
        "export_csv_label": "CSV (*.csv)",
        "export_json_label": "JSON (*.json)",
        "new_record": "New Record",
        "tab_data": "Data",
        "tab_schema": "Schema",
        "tab_stats": "Statistics",
        "tab_sql": "SQL",
        "search_data_placeholder": "Search data...",
        "search_btn": "Search",
        "clear_btn": "Clear",
        "prev": "Previous",
        "next": "Next",
        "page_of": "of",
        "lines": "lines",
        "exec_sql": "Execute",
        "tab_history": "History",
        "tab_favorites": "Favorites",
        "footer_author": "Author: Carlos Canuto Costa",
        "edit": "Edit",
        "delete": "Delete",
        "rename": "Rename",
        "warning": "Warning",
        "error": "Error",
        "success": "Success",
        "confirm": "Confirm",
        "db_empty_warning": "The database is empty. You can import a CSV.",
        "restart_msg": "Please restart the application to apply the new language.",
        "load_db_first": "Please load a database first.",
        "enter_table_name": "New table name:",
        "vacuum_confirm": "Do you want to vacuum the database?\n\nThis action rewrites the database file to recover unused space and might take some time.",
        "vacuum_success": "Database vacuumed successfully.",
        "confirm_delete_record": "Are you sure you want to delete record with rowid {}?",
        "confirm_delete_table": "Are you sure you want to delete table '{}'?\nThis action is irreversible.",
        "record_updated": "Record updated.",
        "record_inserted": "Record inserted successfully.",
        "export_success": "Exported!",
        "no_data_export": "No data to export in this tab.",
        "tooltip_load_db": "Open a SQLite database file",
        "tooltip_import_csv": "Import a CSV file into a new table",
        "tooltip_new_table": "Create a new empty table",
        "tooltip_vacuum": "Optimize database file size",
        "tooltip_export": "Export visible data to CSV or JSON",
        "tooltip_new_record": "Insert a new row into the current table",
        "tooltip_run_sql": "Execute SQL command (Ctrl+Enter)",
        "cancel": "Cancel",
        "save": "Save",
        "insert": "Insert",
        "edit_values": "Edit Values",
        "fill_values": "Fill in Values",
        "rename_table_prompt": "New name for table '{}':",
        "no_stats_data": "Insufficient data for statistics.",
        "no_columns_analyze": "No columns to analyze.",
        "stats_table": "Table:",
        "stats_sample": "Sample analyzed:",
        "stats_filled": "filled:",
        "stats_empty": "empty:",
        "stats_top_values": "top values:",
        "stats_no_data": "no data",
        "stats_error": "Error generating statistics: {}",
        "export_error": "Error exporting: {}",
        "file_loaded": "File:",
        "table_label": "Table:",
        "select_csv_title": "Select CSV File",
        "table_name_title": "Table Name",
        "btn_pandas_stats": "📊 Pandas Report",
        "title_pandas_stats": "Advanced Statistics (Pandas)",
        "calculating_stats": "Calculating statistics...",
        "processing_column": "Processing column: {}",
        "op_cancelled": "Operation cancelled.",
        "stats_unique": "unique:",
        "stats_min": "min:",
        "stats_max": "max:",
        "stats_avg": "avg:",
        "export_stats_btn": "💾 Save JSON",
        "stats_saved": "Statistics exported to: {}",
    }
}